/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 07:24:25 GMT 2022
 */

package com.thealgorithms.dynamicprogramming;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.dynamicprogramming.NewManShanksPrime;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NewManShanksPrime_ESTest extends NewManShanksPrime_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = 1707;
      NewManShanksPrime.nthManShanksPrime(1707, 1707);
      NewManShanksPrime newManShanksPrime0 = new NewManShanksPrime();
      NewManShanksPrime.nthManShanksPrime(1707, 1707);
      NewManShanksPrime.nthManShanksPrime(1707, 1707);
      NewManShanksPrime.nthManShanksPrime(1707, 1707);
      NewManShanksPrime.nthManShanksPrime(1707, 1707);
      int int1 = 2312;
      // Undeclared exception!
      NewManShanksPrime.nthManShanksPrime(2312, 1707);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = 2;
      NewManShanksPrime.nthManShanksPrime(2, 2);
      int int1 = 1733;
      int int2 = (-1);
      NewManShanksPrime.nthManShanksPrime(1733, (-1));
      NewManShanksPrime newManShanksPrime0 = new NewManShanksPrime();
      int int3 = 310;
      NewManShanksPrime.nthManShanksPrime(1733, 310);
      int int4 = (-4382);
      // Undeclared exception!
      try { 
        NewManShanksPrime.nthManShanksPrime((-4382), 0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.dynamicprogramming.NewManShanksPrime", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = 0;
      int int1 = 0;
      // Undeclared exception!
      try { 
        NewManShanksPrime.nthManShanksPrime(0, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        NewManShanksPrime.nthManShanksPrime(0, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NewManShanksPrime.nthManShanksPrime(1, 1);
      NewManShanksPrime newManShanksPrime0 = new NewManShanksPrime();
      int int0 = (-1639);
      // Undeclared exception!
      try { 
        NewManShanksPrime.nthManShanksPrime((-1639), 1);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.dynamicprogramming.NewManShanksPrime", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NewManShanksPrime newManShanksPrime0 = new NewManShanksPrime();
      int int0 = 2;
      NewManShanksPrime.nthManShanksPrime(2, 2);
      NewManShanksPrime.nthManShanksPrime(2, 2);
      NewManShanksPrime.nthManShanksPrime(2, 2);
      NewManShanksPrime.nthManShanksPrime(2, 2);
      int int1 = 0;
      NewManShanksPrime.nthManShanksPrime(1713, 0);
      int int2 = (-2082);
      // Undeclared exception!
      try { 
        NewManShanksPrime.nthManShanksPrime((-2082), (-2673));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.dynamicprogramming.NewManShanksPrime", e);
      }
  }
}
